version: "2.4"

services:
  odoo:
    platform: linux/amd64
    build:
      context: ./odoo
      args:
        DB_VERSION: "15"
        ODOO_VERSION: "17.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    environment:
      EMAIL_FROM: "contact@openspp.org"
      PGDATABASE: &dbname prod
      PGUSER: &dbuser "odoo"
      PROXY_MODE: "false"
      LIST_DB: "true"
    tty: true
    volumes:
      - filestore:/var/lib/odoo:z

  db:
    platform: linux/amd64
    image: ghcr.io/openspp/postgis-autoconf:15-alpine
    shm_size: 4gb
    environment:
      POSTGRES_DB: *dbname
      POSTGRES_USER: *dbuser
      CONF_EXTRA: |
        work_mem = 512MB
    volumes:
      - db:/var/lib/postgresql/data:z

  smtpfake:
    platform: linux/amd64
    image: docker.io/mailhog/mailhog
